# Generated by Django 5.1.7 on 2025-03-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('shipped', 'Shipped'), ('pending', 'Pending'), ('processing', 'Processing')], default='pending', max_length=20),
        ),
    ]
